app = "google-speech-to-text-stream"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1 

[[http_service.checks]]
  interval = "30s"        # Increased from 10s
  timeout = "10s"         # Increased from 2s  
  grace_period = "30s"    # Increased from 5s
  method = "GET"
  path = "/"

[env]
  NODE_ENV = "production"
  PORT = "8080"